#!/bin/bash

# doas
alias su="gum confirm 'root?' && sudo -s || echo 'never mind'"

# exa
alias ls="exa -a1 --icons --group-directories-first"
alias tree="exa -T"

# cd
alias cdtemp='cd $(mktemp -d)'
mkcd() {
    mkdir -pv "$@" && cd "$_" || exit
}
# alias mkdir='mkcd'

alias neofetch="pfetch"
alias stopwatch='time cat'
alias x='exit'
alias curl_wget="curl -JLO "

big() {
    du -h $1 | awk '{print $1}'
}

man() {
    /usr/bin/man $* | \
	col -b | \
	nvim -R -c 'set ft=man nomod nolist' -
    }

killall() {
    kill $(pgrep $1)
}

alias gs='git status -sb'
alias tmux="TERM=screen-256color-bce tmux"
alias uuid="python -c 'import sys,uuid; sys.stdout.write(uuid.uuid4().hex)'"
