#!/bin/bash

#doas
alias s="sudo"
alias su="sudo -s"

#exa
alias ls="ls -a1 --icons --group-directories-first"
alias tree="exa -T"

alias feh="feh --no-fehbg "

#cd
alias cdtemp='cd $(mktemp -d)'
mkcd() {
	mkdir -pv "$@" && cd "$_" || exit
}
alias mkdir='mkcd'

alias wm_test="Xephyr :5 & sleep 1 ; DISPLAY=:5 "
alias neofetch="pfetch"
