#!/bin/bash

#doas
alias s="sudo"
alias su="gum confirm 'root?' && sudo -s || echo 'never mind'"

#exa
alias ls="ls -a1 --icons --group-directories-first"
alias tree="exa -T"

alias feh="feh --no-fehbg "

alias e="$EDITOR"

#cd
alias cdtemp='cd $(mktemp -d)'
mkcd() {
	mkdir -pv "$@" && cd "$_" || exit
}
alias mkdir='mkcd'

alias wm_test="Xephyr :5 & sleep 1 ; DISPLAY=:5 "
alias neofetch="pfetch"
alias stopwatch='time cat'
alias wget='curl -O --retry 999 --retry-max-time 0 -C '
alias wget='curl -O '
