#!/bin/bash

pkg=dnf
# sudo=sudo
sudo=doas

if [ "$1" ]; then
  case "$1" in
    i)         "$pkg" install "$2" ;;
    si)  $sudo "$pkg" install "$2" ;;
    r)         "$pkg" remove  "$2" ;;
    sr)  $sudo "$pkg" remove  "$2" ;;
    up)        "$pkg" update       ;;
	sup) $sudo "$pkg" update       ;;
	c)         "$pkg" clean all    ;;
	sc)  $sudo "$pkg" clean all    ;;

    *)  echo "unknown command" ;;
  esac
else
  echo "Please specify command"
fi
