#!/bin/bash
~/.config/waybar/launch.sh
swaybg -i ~/Pictures/wallpaper/wallpaper.jpg &

# River Config
## Border Color
riverctl border-color-focused 0x88C0D0
riverctl border-color-unfocused 0xD8DEE9

## Tiling
rivertile -main-ratio 0.5 &
riverctl output-layout rivertile

riverctl focus-follows-cursor always

## Keyboard Shortcuts
mod="Mod4"
alt="Mod1"
riverctl map normal $mod Q close
riverctl map normal $mod+Shift Q exit
riverctl map normal $mod X spawn 'alacritty'
riverctl map normal $mod B spawn 'brave'
riverctl map normal Super F toggle-fullscreen
riverctl map normal $mod+Shift F toggle-float
riverctl map normal $mod spawn "rofi -show drun"

for i in {0..9}; do
    riverctl map normal $mod $(($i + 1)) set-focused-tags $((1 << $i))
done

riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

riverctl map normal None XF86AudioRaiseVolume  spawn 'pactl set-sink-volume 0 +5%'
riverctl map normal None XF86AudioLowerVolume  spawn 'pactl set-sink-volume 0 -5%'

