# https://github.com/ChrisTitusTech/mybash
format = """
$directory\
$git_status\
$c\
$elixir\
$elm\
$nodejs\
$golang\
$haskell\
$java\
$julia\
$nim\
$rust\
"""
command_timeout = 5000
# blank line at the start of the prompt
add_newline = true

[directory]
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = ""
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[c]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
format = '[ $symbol $branch ]($style)'

[git_status]
format = '[\[$all_status$ahead_behind\] ]($style)'

[golang]
symbol = ""
format = '[ $symbol ]($style)'

[haskell]
symbol = ""
format = '[ $symbol ]($style)'

[java]
symbol = ""
format = '[ $symbol ]($style)'

[julia]
symbol = ""
format = '[ $symbol ]($style)'

[nodejs]
symbol = ""
format = '[ $symbol ]($style)'

[nim]
symbol = ""
format = '[ $symbol ]($style)'

[rust]
symbol = ""
format = '[ $symbol ]($style)'

[time]
disabled = true 
time_format = "%I:%M" # 12 Hour:Minute Format
format = '[ $time ]($style)'
