format = """
$directory\
$git_branch\
$git_status\
$status
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
format = '[$user ]($style)'

[directory]
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "fg:"#7f85a3"
format = '[$symbol $branch]($style)'

[git_status]
style = "fg:"#7f85a3"
format = '[ $all_status$ahead_behind ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[ $time ]($style)'

[status]
symbol = '[](fg:red)'
success_symbol = '[](fg:green)'
format = '$symbol '
disabled = false
