#!/bin/bash
bash ~/.config/polybar/launch.sh
feh --no-fehbg --bg-fill --randomize ~/Pictures/wallpaper/*
sxhkd &

xsetroot -cursor_name left_ptr

# setxkbmap -option caps:super

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width          3
bspc config window_gap            12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config active_border_color \#E84F4F

bspc rule -a qutebrowser desktop='^1'
bspc rule -a firefox desktop='^1'
bspc rule -a alacritty desktop='^2'
bspc rule -a feh state=floating

