#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --config ~/.config/picom/picom.conf &

xwallpaper --zoom ~/Pictures/wallpaper/wallhaven-zyxvqy_1366x768.png

setxkbmap -option ctrl:nocaps

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a qutebrowser desktop='^1'
bspc rule -a firefox desktop='^1'
bspc rule -a alacritty desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a surf state=tiling
