#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --config ~/.config/picom/picom.conf

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^1'
bspc rule -a Alacritty desktop='^2'
bspc rule -a mplayer2 state=floating
